### ISSUE TITLE
Do you plan on having a release on pypi?

### ISSUE THREAD

**Issue by idgserpro** [collective/collective.twittercards#4]
Nowadays we don't have a release in pypi: https://pypi.python.org/pypi?%3Aaction=search&term=collective.twittercards&submit=search

**Comment by idgserpro** [comment]
@veldman @barseghyanartur @puittenbroek FYI

**Comment by barseghyanartur** [comment]
@idgserpro:

https://pypi.python.org/pypi/collective.twittercards

**Comment by idgserpro** [comment]
Thank you very much guys!
